name: CI
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.os }}

    env:
      GRADLE_ARGS: >-
        --no-daemon
        --max-workers 2
        -Pkotlin.incremental=false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-build-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Compile (macOS)
        if: runner.os == 'macOS'
        run: ./gradlew $GRADLE_ARGS compileKotlinMacosX64

      - name: Test (macOS)
        if: runner.os == 'macOS'
        run: ./gradlew $GRADLE_ARGS macosX64Test

      - name: Assemble (Linux)
        if: runner.os == 'Linux'
        run: ./gradlew $GRADLE_ARGS assemble

      - name: Check (Linux)
        if: runner.os == 'Linux'
        run: ./gradlew $GRADLE_ARGS check

      - name: PublishDocumentation
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew dokkaHtml
          git config user.email CONX_GH_PAGES_USER_EMAIL
          git config user.name CONX_GH_PAGES_USER_NAME
          git fetch
          git checkout gh-pages
          rsync -a core/build/dokka/html/core/ .
          rm -rf core/*
          git add ./com.juul.kable
          git add index.html
          git add package-list
          git commit -m 'Updating dokka documentation'
          git push origin gh-pages
