name: Deploy Documentation
on:
  push:
    #branches: [ $default-branch ]

jobs:
  deploy-documentation:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dokka
        run: |
          ./gradlew dokkaHtml
          ls core/build/dokka/html/

      - name: Deploy
        run: |
          git config user.email "${{ secrets.CONX_GH_PAGES_USER_EMAIL }}"
          git config user.name "${{ secrets.CONX_GH_PAGES_USER_NAME }}"
          git fetch
          git checkout gh-pages
          rsync -av --delete core/build/dokka/html/ .
          git add ./core
          git add ./images
          git add navigation.html
          git add ./scripts
          git add ./styles
          git commit -m 'Updating dokka documentation'
          git push origin gh-pages